<?xml version="1.0"?>

<robot name="sleo" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find sleo_description)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find sleo_description)/urdf/common_properties.urdf.xacro"/> 
  <xacro:include filename="$(find sleo_description)/urdf/sleo_gazebo.urdf.xacro"/>
  <property name="M_PI" value="3.14159"/>

  <!-- Base Size -->
  <property name="base_x_size" value="0.885" />
  <property name="base_y_size" value="0.618" />
  <property name="base_z_size" value="0.391" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.590" />
  <xacro:property name="track" value="0.5936" />
  <xacro:property name="wheel_vertical_offset" value="0.0735" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.127" />
  <xacro:property name="wheel_radius" value="0.1651" />

  <!--Xacro Macro Panther-->
  <xacro:macro name="sleo">

    <!-- Base link is on the ground under the robot -->
    <link name="base_footprint"/>

    <joint name="chassis_joint" type="fixed">
      <origin xyz="0 0 ${wheel_radius - wheel_vertical_offset}" rpy="0 0 0" />
      <parent link="base_footprint" />
      <child link="base_link" />
    </joint>
    
    <!-- Chassis link is the center of the robot's bottom plate -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
	      <mesh filename="package://sleo_description/meshes/chassis.stl"/>
        </geometry>
       <xacro:insert_block name="sleo_black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
	      <mesh filename="package://sleo_description/meshes/chassis.stl"/>
        </geometry>
      </collision>
    </link>
    <gazebo reference="base_link">
    </gazebo>

   <!-- Bonnet link is above of the robot's chassis -->
   <link name="bonnet_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
	      <mesh filename="package://sleo_description/meshes/bonnet.stl"/>
        </geometry>
       <xacro:insert_block name="sleo_green" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
	      <mesh filename="package://sleo_description/meshes/bonnet.stl"/>
        </geometry>
      </collision>
    </link>
    <joint name="bonnet_joint" type="fixed">
      <origin xyz="0 0 0.1384" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="bonnet_link" />
    </joint>

   <!-- Axle link is scatter arround the chassis -->
   <link name="axle_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
	      <mesh filename="package://sleo_description/meshes/axle.stl"/>
        </geometry>
       <xacro:insert_block name="sleo_yellow" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
	      <mesh filename="package://sleo_description/meshes/axle.stl"/>
        </geometry>
      </collision>
    </link>
    <joint name="axle_joint" type="fixed">
      <origin xyz="0 0 0.0235" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="axle_link" />
    </joint>
  
   <!-- Interial link stores the robot's inertial information -->
    <link name="inertial_link">
      <inertial>
        <mass value="59.488"/>
        <origin xyz="0.0 0.0 0" />
        <inertia ixx="2.562164852" ixy="-0.003417247" ixz="0.040864606" iyy="2.562164852" iyz="0.000869143" izz="5.621439416"/>
      </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0.00035 0.00057 0.0000014" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>

    <!-- IMU Link is the standard mounting position for the UM6 IMU.-->
    <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
    <link name="imu_link"/>

    <joint name="imu_joint" type="fixed">
      <origin xyz="0.21659 0 0.046" rpy="-3.1415926 0 0" />
      <parent link="base_link" />
      <child link="imu_link" />
    </joint>
    <gazebo reference="imu_link"/>

    <!-- sleo wheel macros-->
    <xacro:sleo_wheel wheel_prefix="front_left">
      <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:sleo_wheel>
    <xacro:sleo_wheel wheel_prefix="front_right">
      <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:sleo_wheel>   
    <xacro:sleo_wheel wheel_prefix="rear_left">
      <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:sleo_wheel>
    <xacro:sleo_wheel wheel_prefix="rear_right">
      <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:sleo_wheel> 


    <!-- sleo Gazebo simulation details -->
    <sleo_robot_gazebo/>
    <gazebo_material link="base_link" color="Black"/>
    <gazebo_material link="bonnet_link" color="Green"/>
    <gazebo_material link="axle_link" color="Yellow"/>

  </xacro:macro>  
  
</robot>
